function create_events_json(tgt_dir, opt, task_idx)

task = opt.task_name{task_idx};

opts.indent = opt.indent;

filename = fullfile(tgt_dir, ['task-' task '_events.json']);

fprintf('\n creating %s', filename)

% create corresponding data dictionary
content.onset = struct(...
    'LongName', 'event onset', ...
    'Description', ' ', ...
    'Levels', struct(), ...
    'Units', 'seconds',...
    'TermURL', ' ');
content.duration = struct(...
    'LongName', 'event duration', ...
    'Description', ' ', ...
    'Levels', struct(), ...
    'Units', 'seconds',...
    'TermURL', ' ');
content.odorant = struct(...
    'LongName', 'odorant', ...
    'Description', ' ', ...
    'Levels', struct('ch3', 'channel 3'), ...
    'Units', ' ',...
    'TermURL', ' ');

spm_jsonwrite(filename, content, opts)