function create_participants_tsv(tgt_dir, ls_sub_id, age, gender)

gender = gender';
gender = gender(:);
gender( cellfun(@isempty,gender) ) = [];

age = age';
age = age(:);
age(age==0) = [];

p = struct(...
    'participant_id',{ls_sub_id}, ...
    'sex', {gender}, ...
    'age', age);

filename = fullfile(tgt_dir, 'participants.json');

opts.indent = '    ';

spm_save(fullfile(tgt_dir, 'participants.tsv'), p)

% create corresponding data dictionary
content.participant_id = struct(...
    'LongName', 'participant ID', ...
    'Description', ' ', ...
    'Levels', struct(), ...
    'Units', ' ',...
    'TermURL', ' ');
content.age = struct(...
    'LongName', 'age', ...
    'Description', ' ', ...
    'Levels', struct(), ...
    'Units', 'years from birth',...
    'TermURL', ' ');
content.sex = struct(...
    'LongName', 'gender', ...
    'Description', ' ', ...
    'Levels', struct('M', 'male', 'F', 'female'), ...
    'Units', ' ',...
    'TermURL', ' ');

spm_jsonwrite(filename, content, opts)

end
